INSERT INTO Clients VALUES (N'Давыдова', N'Марианна')
INSERT INTO Clients VALUES (N'Тарасов', N'Александр')
INSERT INTO Clients VALUES (N'Жилина', N'Мира')
INSERT INTO Clients VALUES (N'Козловский', N'Сергей')
INSERT INTO Clients VALUES (N'Журавлева', N'Ясмина')
INSERT INTO Clients VALUES (N'Крюков', N'Максим')
INSERT INTO Clients VALUES (N'Кузнецов', N'Гордей')
INSERT INTO Clients VALUES (N'Ильин', N'Лев', N'Кириллович')
INSERT INTO Clients VALUES (N'Кузнецов', N'Михаил')
INSERT INTO Clients VALUES (N'Васильев', N'Семён')
INSERT INTO Clients VALUES (N'Архипова', N'Алиса')
INSERT INTO Clients VALUES (N'Степанов', N'Александр')
INSERT INTO Clients VALUES (N'Москвин', N'Матвей')
INSERT INTO Clients VALUES (N'Маркова', N'Анастасия')
INSERT INTO Clients VALUES (N'Журавлева', N'Мария')


INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (1, 10, 0, 88400)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (2, 20, 0, 56000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (3, 30, 0, 52100)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (4, 40, 0, 34050)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (5, 50, 0, 82000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (6, 60, 0, 63000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (7, 70, 0, 93000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (8, 80, 0, 82000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (9, 90, 0, 74000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (10, 100, 0, 54500)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (11, 110, 0, 25000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (12, 120, 0, 75000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (13, 130, 0, 44400)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (14, 140, 0, 46000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (15, 150, 0, 40650)

INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (1, 15, 1, 77000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (2, 25, 1, 37500)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (3, 35, 1, 41000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (4, 45, 1, 42000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (5, 55, 1, 46000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (6, 65, 1, 45000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (7, 75, 1, 42560)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (8, 85, 1, 42500)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (9, 95, 1, 49500)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (10, 105, 1, 47500)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (11, 115, 1, 43000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (12, 125, 1, 95000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (13, 135, 1, 72500)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (14, 145, 1, 42500)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (15, 155, 1, 33400)

INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (1, 115, 1, 43000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (2, 125, 0, 72000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (3, 135, 1, 24000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (4, 145, 0, 52000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (5, 155, 1, 95000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (6, 165, 0, 55070)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (7, 175, 1, 59000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (8, 185, 0, 25400)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (9, 195, 1, 65080)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (10, 1105, 0, 35050)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (11, 1115, 0, 95000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (12, 1125, 1, 83000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (13, 1135, 0, 52000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (14, 1145, 1, 75000)
INSERT INTO Accounts(ClientId, AccountNumber, IsDeposit, Balance) VALUES (15, 1155, 0, 89000)